// Catálogo de ejercicios y rutinas.
// Imágenes: free-exercise-db (dominio público, Unlicense) → img/ex/<img>/0.jpg (inicio) y 1.jpg (final).

export const MUSCLES = {
  quads: 'Cuádriceps',
  hamstrings: 'Isquiotibiales',
  glutes: 'Glúteos',
  chest: 'Pecho',
  back: 'Espalda',
  sideDelts: 'Hombro lateral',
  triceps: 'Tríceps',
  biceps: 'Bíceps',
  calves: 'Gemelos',
};

// Series semanales objetivo por músculo (rango de hipertrofia con 2–3 días).
export const WEEKLY_TARGET = { min: 8, max: 15 };

export const EXERCISES = {
  squat: {
    name: 'Sentadilla profunda',
    img: 'Barbell_Full_Squat',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings'],
    increment: 2.5,
    why: 'Mejor relación estímulo/tiempo para piernas. Bajar profundo hace crecer más glúteo y aductores que la media sentadilla (Kubo 2019).',
    cues: [
      'Pies a la anchura de hombros, puntas ligeramente hacia fuera.',
      'Inhala, aprieta el abdomen y baja como sentándote entre los talones.',
      'Rodillas siguen la dirección de las puntas de los pies.',
      'Baja hasta que el muslo quede al menos paralelo al suelo.',
      'Sube empujando todo el pie, pecho arriba.',
    ],
    mistakes: ['Rodillas hacia dentro', 'Levantar los talones', 'Redondear la zona lumbar abajo', 'Quedarse corto de profundidad'],
    alternatives: ['hackSquat', 'legPress', 'splitSquat'],
  },
  hackSquat: {
    name: 'Hack squat',
    img: 'Hack_Squat',
    primary: ['quads', 'glutes'],
    secondary: [],
    increment: 5,
    why: 'Alternativa estable a la sentadilla: menos técnica y fatiga lumbar, mismo estímulo en cuádriceps.',
    cues: ['Espalda pegada al respaldo.', 'Baja hasta lo más profundo que puedas sin despegar la cadera.', 'No bloquees las rodillas arriba.'],
    mistakes: ['Rango corto', 'Despegar la cadera del respaldo'],
    alternatives: ['squat', 'legPress'],
  },
  legPress: {
    name: 'Prensa de piernas',
    img: 'Leg_Press',
    primary: ['quads', 'glutes'],
    secondary: [],
    increment: 5,
    why: 'Permite cargar mucho las piernas con poco riesgo y poca fatiga general.',
    cues: ['Pies a la anchura de hombros en el centro de la plataforma.', 'Baja hasta que las rodillas se acerquen al pecho sin que la pelvis se despegue.', 'Empuja sin bloquear las rodillas.'],
    mistakes: ['Despegar la zona lumbar del asiento', 'Recorrido corto', 'Bloquear las rodillas'],
    alternatives: ['squat', 'hackSquat', 'splitSquat'],
  },
  splitSquat: {
    name: 'Sentadilla búlgara',
    img: 'Split_Squat_with_Dumbbells',
    primary: ['quads', 'glutes'],
    secondary: [],
    increment: 2,
    why: 'Unilateral: gran estiramiento del glúteo y cuádriceps, con cargas bajas. Ideal si no hay rack libre.',
    cues: ['Pie trasero apoyado en un banco.', 'Baja recto hasta que la rodilla trasera casi toque el suelo.', 'Torso ligeramente inclinado para más glúteo.'],
    mistakes: ['Paso demasiado corto', 'Perder el equilibrio por prisa'],
    alternatives: ['squat', 'legPress'],
  },
  rdl: {
    name: 'Peso muerto rumano',
    img: 'Romanian_Deadlift',
    primary: ['hamstrings', 'glutes'],
    secondary: ['back'],
    increment: 2.5,
    why: 'Carga los isquios y glúteos en posición estirada, la más efectiva para crecer.',
    cues: [
      'Rodillas un poco flexionadas y fijas.',
      'Lleva la cadera hacia atrás, la barra pegada a las piernas.',
      'Espalda neutra; baja hasta sentir un estiramiento fuerte en los isquios (normalmente media tibia).',
      'Sube empujando la cadera hacia delante.',
    ],
    mistakes: ['Redondear la espalda', 'Convertirlo en sentadilla (doblar mucho las rodillas)', 'Separar la barra del cuerpo'],
    alternatives: [],
  },
  seatedLegCurl: {
    name: 'Curl femoral sentado',
    img: 'Seated_Leg_Curl',
    primary: ['hamstrings'],
    secondary: [],
    increment: 2.5,
    why: 'Sentado, la cadera flexionada estira más los isquios: crece más que el curl tumbado (Maeo 2021).',
    cues: ['Ajusta el rodillo justo encima de los tobillos.', 'Inclina el torso ligeramente hacia delante para más estiramiento.', 'Controla la subida 2–3 s.'],
    mistakes: ['Soltar el peso de golpe', 'Rango incompleto'],
    alternatives: ['lyingLegCurl'],
  },
  lyingLegCurl: {
    name: 'Curl femoral tumbado',
    img: 'Lying_Leg_Curls',
    primary: ['hamstrings'],
    secondary: [],
    increment: 2.5,
    why: 'Alternativa si no hay máquina sentada.',
    cues: ['Cadera pegada al banco.', 'Sube hasta el máximo y baja controlado.'],
    mistakes: ['Levantar la cadera para ayudarte'],
    alternatives: ['seatedLegCurl'],
  },
  inclineDbPress: {
    name: 'Press inclinado con mancuernas',
    img: 'Incline_Dumbbell_Press',
    primary: ['chest'],
    secondary: ['triceps'],
    increment: 2,
    why: 'Pecho completo (con énfasis en la parte alta) y más estiramiento que con barra.',
    cues: ['Banco a 30°.', 'Escápulas atrás y abajo, pies firmes.', 'Baja las mancuernas hasta sentir estiramiento en el pecho, codos a ~45°.', 'Empuja hacia arriba y ligeramente adentro.'],
    mistakes: ['Banco demasiado inclinado (se vuelve hombro)', 'Rebotar abajo', 'Codos abiertos a 90°'],
    alternatives: ['benchPress', 'dips'],
  },
  benchPress: {
    name: 'Press de banca',
    img: 'Barbell_Bench_Press_-_Medium_Grip',
    primary: ['chest'],
    secondary: ['triceps'],
    increment: 2.5,
    why: 'El básico de empuje: fácil de progresar en carga.',
    cues: ['Agarre algo más ancho que los hombros.', 'Escápulas retraídas, ligero arco.', 'Baja la barra a la parte baja del pecho, controlado.', 'Empuja hacia arriba y un poco hacia atrás.'],
    mistakes: ['Rebotar en el pecho', 'Levantar la cadera', 'Codos a 90°'],
    alternatives: ['inclineDbPress', 'dips'],
  },
  dips: {
    name: 'Fondos en paralelas',
    img: 'Dips_-_Chest_Version',
    primary: ['chest'],
    secondary: ['triceps'],
    increment: 2.5,
    why: 'Gran estiramiento del pecho bajo y mucho tríceps. Se puede lastrar.',
    cues: ['Inclina el torso hacia delante.', 'Baja hasta que los hombros queden por debajo de los codos si no hay molestia.', 'Sube sin bloquear bruscamente.'],
    mistakes: ['Bajar poco', 'Encoger los hombros hacia las orejas'],
    alternatives: ['benchPress', 'inclineDbPress'],
  },
  latPulldown: {
    name: 'Jalón al pecho',
    img: 'Wide-Grip_Lat_Pulldown',
    primary: ['back'],
    secondary: ['biceps'],
    increment: 2.5,
    why: 'Dorsales amplios. Fácil de ajustar la carga y de estirar arriba.',
    cues: ['Agarre algo más ancho que hombros.', 'Deja que los brazos se estiren por completo arriba.', 'Tira llevando los codos hacia abajo y a los costados, pecho arriba.'],
    mistakes: ['Echarse muy atrás', 'Tirar con los bíceps', 'No estirar arriba'],
    alternatives: ['pullups'],
  },
  pullups: {
    name: 'Dominadas',
    img: 'Pullups',
    primary: ['back'],
    secondary: ['biceps'],
    increment: 2.5,
    why: 'Igual de efectivas que el jalón; úsalas si haces más de 6 repeticiones.',
    cues: ['Parte colgado con brazos estirados.', 'Tira de los codos hacia las costillas hasta pasar la barbilla.', 'Baja controlado hasta estirar.'],
    mistakes: ['Balancearse', 'Medias repeticiones'],
    alternatives: ['latPulldown'],
  },
  chestSupportedRow: {
    name: 'Remo con pecho apoyado',
    img: 'Dumbbell_Incline_Row',
    primary: ['back'],
    secondary: ['biceps'],
    increment: 2,
    why: 'Espalda media sin fatigar la zona lumbar (que ya trabaja el rumano).',
    cues: ['Pecho apoyado en un banco a ~30–45°.', 'Brazos estirados abajo, deja que las escápulas se separen.', 'Tira llevando los codos hacia la cadera y junta las escápulas.'],
    mistakes: ['Despegar el pecho del banco', 'Recorrido corto'],
    alternatives: ['cableRow'],
  },
  cableRow: {
    name: 'Remo en polea baja',
    img: 'Seated_Cable_Rows',
    primary: ['back'],
    secondary: ['biceps'],
    increment: 2.5,
    why: 'Tensión constante y buen estiramiento de la espalda.',
    cues: ['Rodillas ligeramente flexionadas, espalda neutra.', 'Estira los brazos por completo dejando avanzar los hombros.', 'Tira hacia el abdomen sin balancear el torso.'],
    mistakes: ['Balancear el torso para mover más peso', 'Encoger los hombros'],
    alternatives: ['chestSupportedRow'],
  },
  lateralRaise: {
    name: 'Elevaciones laterales',
    img: 'Side_Lateral_Raise',
    primary: ['sideDelts'],
    secondary: [],
    increment: 1,
    why: 'El hombro lateral apenas se trabaja con los compuestos y es clave para la amplitud.',
    cues: ['Ligera inclinación del torso hacia delante.', 'Sube los brazos a los lados hasta la altura de los hombros, codos un poco flexionados.', 'Guía el movimiento con los codos, no con las manos.', 'Baja en 2–3 s.'],
    mistakes: ['Usar impulso', 'Subir por encima de los hombros encogiéndolos', 'Peso excesivo'],
    alternatives: ['cableLateralRaise'],
  },
  cableLateralRaise: {
    name: 'Elevación lateral en polea',
    img: 'Cable_Seated_Lateral_Raise',
    primary: ['sideDelts'],
    secondary: [],
    increment: 1,
    why: 'La polea mantiene la tensión abajo, donde la mancuerna no carga.',
    cues: ['Polea baja, cable por delante o por detrás del cuerpo.', 'Sube hasta la altura del hombro y baja lento.'],
    mistakes: ['Encoger los hombros'],
    alternatives: ['lateralRaise'],
  },
  overheadTriceps: {
    name: 'Extensión de tríceps sobre la cabeza',
    img: 'Cable_Rope_Overhead_Triceps_Extension',
    primary: ['triceps'],
    secondary: [],
    increment: 2.5,
    why: 'Con el brazo arriba, la cabeza larga del tríceps se estira: ~40 % más crecimiento que el jalón (Maeo 2023).',
    cues: ['De espaldas a la polea, cuerda detrás de la cabeza.', 'Codos apuntando al frente y fijos.', 'Estira los brazos por completo y vuelve hasta sentir el estiramiento.'],
    mistakes: ['Abrir los codos', 'Mover los hombros', 'Rango corto abajo'],
    alternatives: [],
  },
  inclineCurl: {
    name: 'Curl inclinado con mancuernas',
    img: 'Incline_Dumbbell_Curl',
    primary: ['biceps'],
    secondary: [],
    increment: 1,
    why: 'Brazo por detrás del torso: el bíceps trabaja estirado, donde más crece.',
    cues: ['Banco a 45–60°, brazos colgando por detrás del cuerpo.', 'Sube sin adelantar los codos.', 'Baja lento hasta estirar por completo.'],
    mistakes: ['Adelantar los codos', 'Balancear', 'No estirar abajo'],
    alternatives: [],
  },
  calfRaise: {
    name: 'Elevación de gemelos de pie',
    img: 'Standing_Calf_Raises',
    primary: ['calves'],
    secondary: [],
    increment: 5,
    why: 'De pie con rodillas estiradas se trabaja el gastrocnemio; la pausa abajo aprovecha el estiramiento.',
    cues: ['Puntas en el borde del escalón.', 'Baja al máximo y pausa 1–2 s abajo.', 'Sube hasta la punta sin rebotar.'],
    mistakes: ['Rebotar', 'Rango corto', 'Flexionar las rodillas'],
    alternatives: [],
  },
};

// Cada "slot" es un hueco de la rutina que el usuario puede sustituir por una alternativa.
// superset: slots con la misma letra se alternan con descanso corto.
export const ROUTINES = {
  A: {
    name: 'Full Body A',
    slots: [
      { id: 'A1', exercise: 'squat', sets: 3, reps: [6, 10], rest: 180 },
      { id: 'A2', exercise: 'inclineDbPress', sets: 3, reps: [6, 10], rest: 150 },
      { id: 'A3', exercise: 'latPulldown', sets: 3, reps: [6, 10], rest: 150 },
      { id: 'A4', exercise: 'seatedLegCurl', sets: 3, reps: [10, 15], rest: 90 },
      { id: 'A5', exercise: 'lateralRaise', sets: 3, reps: [12, 20], rest: 60 },
      { id: 'A6', exercise: 'overheadTriceps', sets: 3, reps: [10, 15], rest: 60, superset: 'x' },
      { id: 'A7', exercise: 'inclineCurl', sets: 3, reps: [10, 15], rest: 60, superset: 'x' },
      { id: 'A8', exercise: 'calfRaise', sets: 3, reps: [10, 15], rest: 60 },
    ],
  },
  B: {
    name: 'Full Body B',
    slots: [
      { id: 'B1', exercise: 'rdl', sets: 3, reps: [6, 10], rest: 180 },
      { id: 'B2', exercise: 'legPress', sets: 3, reps: [8, 12], rest: 150 },
      { id: 'B3', exercise: 'benchPress', sets: 3, reps: [6, 10], rest: 150 },
      { id: 'B4', exercise: 'chestSupportedRow', sets: 3, reps: [8, 12], rest: 120 },
      { id: 'B5', exercise: 'lateralRaise', sets: 3, reps: [12, 20], rest: 60 },
      { id: 'B6', exercise: 'overheadTriceps', sets: 3, reps: [10, 15], rest: 60, superset: 'x' },
      { id: 'B7', exercise: 'inclineCurl', sets: 3, reps: [10, 15], rest: 60, superset: 'x' },
      { id: 'B8', exercise: 'calfRaise', sets: 3, reps: [10, 15], rest: 60 },
    ],
  },
};

export function imgUrl(exerciseId, frame = 0) {
  return `img/ex/${EXERCISES[exerciseId].img}/${frame}.jpg`;
}
