// Catálogo de ejercicios y rutinas.
// Imágenes: free-exercise-db (dominio público, Unlicense) → img/ex/<img>/0.jpg (inicio) y 1.jpg (final).

export const MUSCLES = {
  quads: 'Cuádriceps',
  hamstrings: 'Isquiotibiales',
  glutes: 'Glúteos',
  chest: 'Pecho',
  back: 'Espalda',
  sideDelts: 'Hombro lateral',
  triceps: 'Tríceps',
  biceps: 'Bíceps',
  calves: 'Gemelos',
  rearDelts: 'Hombro posterior',
  forearms: 'Antebrazo',
};

// Series semanales objetivo por músculo (rango de hipertrofia con 2–3 días).
export const WEEKLY_TARGET = { min: 8, max: 15 };

export const EXERCISES = {
  squat: {
    leg: true,
    name: 'Sentadilla profunda',
    img: 'Barbell_Full_Squat',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings'],
    increment: 2.5,
    why: 'Mejor relación estímulo/tiempo para piernas. Bajar profundo hace crecer más glúteo y aductores que la media sentadilla (Kubo 2019).',
    cues: [
      'Pies a la anchura de hombros, puntas ligeramente hacia fuera.',
      'Inhala, aprieta el abdomen y baja como sentándote entre los talones.',
      'Rodillas siguen la dirección de las puntas de los pies.',
      'Baja hasta que el muslo quede al menos paralelo al suelo.',
      'Sube empujando todo el pie, pecho arriba.',
    ],
    mistakes: ['Rodillas hacia dentro', 'Levantar los talones', 'Redondear la zona lumbar abajo', 'Quedarse corto de profundidad'],
    alternatives: ['hsLegPress', 'hackSquat', 'legPress', 'splitSquat'],
  },
  hackSquat: {
    leg: true, gym: true,
    name: 'Hack squat',
    img: 'Hack_Squat',
    primary: ['quads', 'glutes'],
    secondary: [],
    increment: 5,
    why: 'Alternativa estable a la sentadilla: menos técnica y fatiga lumbar, mismo estímulo en cuádriceps. Es bilateral: la pierna sana puede compensar sin que lo notes, así que en recuperación va ligera y controlada.',
    cues: ['Espalda pegada al respaldo.', 'Pies a la anchura de hombros, en el centro de la plataforma.', 'Baja controlado (2–3 s) hasta donde no haya molestia en la tibia ni en la rodilla.', 'No bloquees las rodillas arriba.', 'Reparte el peso por igual: si notas que cargas más en la pierna sana, baja el peso.'],
    mistakes: ['Rango corto', 'Despegar la cadera del respaldo', 'Cargar más la pierna sana'],
    alternatives: ['hsLegPress', 'legPress'],
  },
  legPress: {
    leg: true,
    name: 'Prensa de piernas',
    img: 'Leg_Press',
    primary: ['quads', 'glutes'],
    secondary: [],
    increment: 5,
    why: 'Permite cargar mucho las piernas con poco riesgo y poca fatiga general.',
    cues: ['Pies a la anchura de hombros en el centro de la plataforma.', 'Baja hasta que las rodillas se acerquen al pecho sin que la pelvis se despegue.', 'Empuja sin bloquear las rodillas.'],
    mistakes: ['Despegar la zona lumbar del asiento', 'Recorrido corto', 'Bloquear las rodillas'],
    alternatives: ['squat', 'hackSquat', 'splitSquat'],
  },
  splitSquat: {
    leg: true, unilateral: true,
    name: 'Sentadilla búlgara',
    img: 'Split_Squat_with_Dumbbells',
    primary: ['quads', 'glutes'],
    secondary: [],
    increment: 2,
    why: 'Unilateral: gran estiramiento del glúteo y cuádriceps, con cargas bajas. Ideal si no hay rack libre.',
    cues: ['Pie trasero apoyado en un banco.', 'Baja recto hasta que la rodilla trasera casi toque el suelo.', 'Torso ligeramente inclinado para más glúteo.'],
    mistakes: ['Paso demasiado corto', 'Perder el equilibrio por prisa'],
    alternatives: ['squat', 'legPress'],
  },
  rdl: {
    leg: true,
    name: 'Peso muerto rumano',
    img: 'Romanian_Deadlift',
    primary: ['hamstrings', 'glutes'],
    secondary: ['back'],
    increment: 2.5,
    why: 'Carga los isquios y glúteos en posición estirada, la más efectiva para crecer.',
    cues: [
      'Rodillas un poco flexionadas y fijas.',
      'Lleva la cadera hacia atrás, la barra pegada a las piernas.',
      'Espalda neutra; baja hasta sentir un estiramiento fuerte en los isquios (normalmente media tibia).',
      'Sube empujando la cadera hacia delante.',
    ],
    mistakes: ['Redondear la espalda', 'Convertirlo en sentadilla (doblar mucho las rodillas)', 'Separar la barra del cuerpo'],
    alternatives: [],
  },
  seatedLegCurl: {
    leg: true, unilateral: true, gym: true,
    name: 'Curl femoral sentado',
    img: 'Seated_Leg_Curl',
    primary: ['hamstrings'],
    secondary: [],
    increment: 2.5,
    why: 'Sentado, la cadera flexionada estira más los isquios: crece más que el curl tumbado (Maeo 2021).',
    cues: ['Ajusta el rodillo justo encima de los tobillos (comprueba que no presione la zona de la fractura).', 'Una pierna cada vez: empieza por la lesionada.', 'Inclina el torso ligeramente hacia delante para más estiramiento.', 'Controla la subida 2–3 s.'],
    mistakes: ['Soltar el peso de golpe', 'Rango incompleto'],
    alternatives: ['lyingLegCurl'],
  },
  lyingLegCurl: {
    leg: true, unilateral: true,
    name: 'Curl femoral tumbado',
    img: 'Lying_Leg_Curls',
    primary: ['hamstrings'],
    secondary: [],
    increment: 2.5,
    why: 'Alternativa si no hay máquina sentada.',
    cues: ['Cadera pegada al banco.', 'Sube hasta el máximo y baja controlado.'],
    mistakes: ['Levantar la cadera para ayudarte'],
    alternatives: ['seatedLegCurl'],
  },
  inclineDbPress: {
    name: 'Press inclinado con mancuernas',
    img: 'Incline_Dumbbell_Press',
    primary: ['chest'],
    secondary: ['triceps'],
    increment: 2,
    why: 'Pecho completo (con énfasis en la parte alta) y más estiramiento que con barra.',
    cues: ['Banco a 30°.', 'Escápulas atrás y abajo, pies firmes.', 'Baja las mancuernas hasta sentir estiramiento en el pecho, codos a ~45°.', 'Empuja hacia arriba y ligeramente adentro.'],
    mistakes: ['Banco demasiado inclinado (se vuelve hombro)', 'Rebotar abajo', 'Codos abiertos a 90°'],
    alternatives: ['hsInclinePress', 'benchPress', 'dips'],
  },
  benchPress: {
    name: 'Press de banca',
    img: 'Barbell_Bench_Press_-_Medium_Grip',
    primary: ['chest'],
    secondary: ['triceps'],
    increment: 2.5,
    why: 'El básico de empuje: fácil de progresar en carga.',
    cues: ['Agarre algo más ancho que los hombros.', 'Escápulas retraídas, ligero arco.', 'Baja la barra a la parte baja del pecho, controlado.', 'Empuja hacia arriba y un poco hacia atrás.'],
    mistakes: ['Rebotar en el pecho', 'Levantar la cadera', 'Codos a 90°'],
    alternatives: ['inclineDbPress', 'dips'],
  },
  dips: {
    name: 'Fondos en paralelas',
    img: 'Dips_-_Chest_Version',
    primary: ['chest'],
    secondary: ['triceps'],
    increment: 2.5,
    why: 'Gran estiramiento del pecho bajo y mucho tríceps. Se puede lastrar.',
    cues: ['Inclina el torso hacia delante.', 'Baja hasta que los hombros queden por debajo de los codos si no hay molestia.', 'Sube sin bloquear bruscamente.'],
    mistakes: ['Bajar poco', 'Encoger los hombros hacia las orejas'],
    alternatives: ['benchPress', 'inclineDbPress'],
  },
  latPulldown: {
    name: 'Jalón al pecho',
    img: 'Wide-Grip_Lat_Pulldown',
    primary: ['back'],
    secondary: ['biceps'],
    increment: 2.5,
    why: 'Dorsales amplios. Fácil de ajustar la carga y de estirar arriba.',
    cues: ['Agarre algo más ancho que hombros.', 'Deja que los brazos se estiren por completo arriba.', 'Tira llevando los codos hacia abajo y a los costados, pecho arriba.'],
    mistakes: ['Echarse muy atrás', 'Tirar con los bíceps', 'No estirar arriba'],
    alternatives: ['pullups'],
  },
  pullups: {
    name: 'Dominadas',
    img: 'Pullups',
    primary: ['back'],
    secondary: ['biceps'],
    increment: 2.5,
    why: 'Igual de efectivas que el jalón; úsalas si haces más de 6 repeticiones.',
    cues: ['Parte colgado con brazos estirados.', 'Tira de los codos hacia las costillas hasta pasar la barbilla.', 'Baja controlado hasta estirar.'],
    mistakes: ['Balancearse', 'Medias repeticiones'],
    alternatives: ['latPulldown'],
  },
  chestSupportedRow: {
    name: 'Remo con pecho apoyado',
    img: 'Dumbbell_Incline_Row',
    primary: ['back'],
    secondary: ['biceps'],
    increment: 2,
    why: 'Espalda media sin fatigar la zona lumbar (que ya trabaja el rumano).',
    cues: ['Pecho apoyado en un banco a ~30–45°.', 'Brazos estirados abajo, deja que las escápulas se separen.', 'Tira llevando los codos hacia la cadera y junta las escápulas.'],
    mistakes: ['Despegar el pecho del banco', 'Recorrido corto'],
    alternatives: ['machineRow', 'cableRow'],
  },
  cableRow: {
    name: 'Remo en polea baja',
    img: 'Seated_Cable_Rows',
    primary: ['back'],
    secondary: ['biceps'],
    increment: 2.5,
    why: 'Tensión constante y buen estiramiento de la espalda.',
    cues: ['Rodillas ligeramente flexionadas, espalda neutra.', 'Estira los brazos por completo dejando avanzar los hombros.', 'Tira hacia el abdomen sin balancear el torso.'],
    mistakes: ['Balancear el torso para mover más peso', 'Encoger los hombros'],
    alternatives: ['chestSupportedRow'],
  },
  lateralRaise: {
    name: 'Elevaciones laterales',
    img: 'Side_Lateral_Raise',
    primary: ['sideDelts'],
    secondary: [],
    increment: 1,
    why: 'El hombro lateral apenas se trabaja con los compuestos y es clave para la amplitud.',
    cues: ['Ligera inclinación del torso hacia delante.', 'Sube los brazos a los lados hasta la altura de los hombros, codos un poco flexionados.', 'Guía el movimiento con los codos, no con las manos.', 'Baja en 2–3 s.'],
    mistakes: ['Usar impulso', 'Subir por encima de los hombros encogiéndolos', 'Peso excesivo'],
    alternatives: ['machineLateral', 'cableLateralRaise'],
  },
  cableLateralRaise: {
    name: 'Elevación lateral en polea',
    img: 'Cable_Seated_Lateral_Raise',
    primary: ['sideDelts'],
    secondary: [],
    increment: 1,
    why: 'La polea mantiene la tensión abajo, donde la mancuerna no carga.',
    cues: ['Polea baja, cable por delante o por detrás del cuerpo.', 'Sube hasta la altura del hombro y baja lento.'],
    mistakes: ['Encoger los hombros'],
    alternatives: ['machineLateral', 'lateralRaise'],
  },
  overheadTriceps: {
    name: 'Extensión de tríceps sobre la cabeza',
    img: 'Cable_Rope_Overhead_Triceps_Extension',
    primary: ['triceps'],
    secondary: [],
    increment: 2.5,
    why: 'Con el brazo arriba, la cabeza larga del tríceps se estira: ~40 % más crecimiento que el jalón (Maeo 2023).',
    cues: ['De espaldas a la polea, cuerda detrás de la cabeza.', 'Codos apuntando al frente y fijos.', 'Estira los brazos por completo y vuelve hasta sentir el estiramiento.'],
    mistakes: ['Abrir los codos', 'Mover los hombros', 'Rango corto abajo'],
    alternatives: ['machineTriceps'],
  },
  inclineCurl: {
    name: 'Curl inclinado con mancuernas',
    img: 'Incline_Dumbbell_Curl',
    primary: ['biceps'],
    secondary: [],
    increment: 1,
    why: 'Brazo por detrás del torso: el bíceps trabaja estirado, donde más crece.',
    cues: ['Banco a 45–60°, brazos colgando por detrás del cuerpo.', 'Sube sin adelantar los codos.', 'Baja lento hasta estirar por completo.'],
    mistakes: ['Adelantar los codos', 'Balancear', 'No estirar abajo'],
    alternatives: ['machineCurl'],
  },
  calfRaise: {
    leg: true,
    name: 'Elevación de gemelos de pie',
    img: 'Standing_Calf_Raises',
    primary: ['calves'],
    secondary: [],
    increment: 5,
    why: 'De pie con rodillas estiradas se trabaja el gastrocnemio; la pausa abajo aprovecha el estiramiento.',
    cues: ['Puntas en el borde del escalón.', 'Baja al máximo y pausa 1–2 s abajo.', 'Sube hasta la punta sin rebotar.'],
    mistakes: ['Rebotar', 'Rango corto', 'Flexionar las rodillas'],
    alternatives: ['calfExtension'],
  },

  // ---------- Máquinas de tu gimnasio ----------
  hsLegPress: {
    leg: true, unilateral: true, gym: true,
    name: 'Prensa Hammer Strength (una pierna)',
    img: 'Leg_Press',
    primary: ['quads', 'glutes'],
    secondary: [],
    increment: 5,
    why: 'Prensa de discos: permite trabajar cada pierna por separado, igualar la lesionada con la sana y subir la carga en saltos pequeños.',
    cues: ['Espalda y cadera pegadas al respaldo.', 'Empieza por la pierna lesionada; la sana hace el mismo peso y reps, no más.', 'Baja controlado (2–3 s) hasta donde no haya molestia.', 'Empuja con todo el pie sin bloquear la rodilla.'],
    mistakes: ['Despegar la cadera', 'Bloquear la rodilla arriba', 'Que la pierna sana haga más que la lesionada'],
    alternatives: ['hackSquat', 'legPress'],
  },
  calfExtension: {
    leg: true, unilateral: true, gym: true,
    name: 'Extensión de gemelos (máquina)',
    img: 'Calf_Press',
    primary: ['calves'],
    secondary: [],
    increment: 5,
    why: 'La carga progresiva y controlada también ayuda a que el hueso se refuerce. Una pierna cada vez para igualarlas.',
    cues: ['Solo la punta del pie en la plataforma.', 'Baja el talón al máximo y pausa 1–2 s en el estiramiento.', 'Sube hasta la punta sin rebotar.'],
    mistakes: ['Rebotar', 'Rango corto', 'Mucho peso con poco recorrido'],
    alternatives: ['calfRaise'],
  },
  hsInclinePress: {
    gym: true,
    name: 'Press inclinado Hammer Strength (MTS)',
    img: 'Leverage_Incline_Chest_Press',
    primary: ['chest'],
    secondary: ['triceps'],
    increment: 2.5,
    why: 'Pecho alto y medio con trayectoria guiada: fácil de llevar cerca del fallo con seguridad. Cada brazo va por separado.',
    cues: ['Ajusta el asiento para que los agarres queden a la altura de la parte alta del pecho.', 'Agarre prono (palmas hacia abajo), escápulas atrás.', 'Empuja hacia arriba y adelante sin bloquear los codos.', 'Vuelve lento hasta sentir el estiramiento del pecho.'],
    mistakes: ['Asiento demasiado alto (se vuelve press de hombro)', 'Despegar la espalda', 'Recorrido corto'],
    alternatives: ['inclineDbPress', 'benchPress'],
  },
  pecFly: {
    gym: true,
    name: 'Pectoral fly (máquina)',
    img: 'Butterfly',
    primary: ['chest'],
    secondary: [],
    increment: 2.5,
    why: 'Aislamiento de pecho con mucha tensión en el estiramiento y sin fatigar tríceps.',
    cues: ['Asiento para que los codos queden un poco por debajo de los hombros.', 'Ajusta la posición inicial para notar estiramiento sin dolor en el hombro.', 'Pecho arriba, hombros atrás, codos ligeramente flexionados.', 'Junta los agarres y vuelve controlado.'],
    mistakes: ['Encoger los hombros', 'Posición inicial demasiado atrás', 'Soltar el peso de golpe'],
    alternatives: ['dips'],
  },
  rearDeltFly: {
    gym: true,
    name: 'Rear delt (misma máquina, al revés)',
    img: 'Reverse_Machine_Flyes',
    primary: ['rearDelts'],
    secondary: ['back'],
    increment: 2.5,
    why: 'Hombro posterior: da volumen visto de lado y de espalda, y equilibra tanto trabajo de empuje.',
    cues: ['Siéntate mirando al respaldo.', 'Asiento para que los brazos queden paralelos al suelo agarrando los mangos internos.', 'Codos ligeramente flexionados; lleva los brazos hacia fuera y atrás, codos a la altura de los agarres.', 'Vuelve controlado.'],
    mistakes: ['Juntar las escápulas en vez de mover los brazos', 'Usar impulso'],
    alternatives: [],
  },
  machineLateral: {
    gym: true,
    name: 'Elevación lateral (máquina)',
    img: 'Cable_Seated_Lateral_Raise',
    primary: ['sideDelts'],
    secondary: [],
    increment: 2.5,
    why: 'Deltoide lateral: lo que más cambia la silueta y que ningún compuesto trabaja bien.',
    cues: ['Ajusta el asiento para alinear los hombros con los ejes de la máquina (las almohadillas no deben deslizarse por el brazo).', 'Siéntate mirando a la máquina, antebrazos en las almohadillas y agarre suave.', 'Sube los codos hasta la altura de los hombros.', 'Baja lento, en 2–3 s.'],
    mistakes: ['Encoger los hombros', 'Subir por encima de los hombros', 'Bajar de golpe'],
    alternatives: ['lateralRaise', 'cableLateralRaise'],
  },
  machineTriceps: {
    gym: true,
    name: 'Extensión de tríceps (máquina)',
    img: 'Machine_Triceps_Extension',
    primary: ['triceps'],
    secondary: [],
    increment: 2.5,
    why: 'Tríceps estable y fácil de llevar al fallo. Altérnala con la extensión en polea sobre la cabeza para estirar más la cabeza larga.',
    cues: ['Ajusta el asiento para que los codos queden alineados con el eje de la máquina.', 'Brazos apoyados en la almohadilla, codos pegados.', 'Extiende por completo y vuelve hasta el máximo estiramiento.'],
    mistakes: ['Despegar los codos de la almohadilla', 'Rango corto'],
    alternatives: ['overheadTriceps'],
  },
  machineCurl: {
    gym: true,
    name: 'Curl de bíceps (máquina)',
    img: 'Machine_Bicep_Curl',
    primary: ['biceps'],
    secondary: [],
    increment: 2.5,
    why: 'Tipo predicador: carga el bíceps estirado, justo donde más crece.',
    cues: ['Ajusta el asiento para que la parte de atrás del brazo apoye entera en la almohadilla y el codo quede en el eje.', 'Sube hasta la contracción y baja lento hasta estirar casi por completo.'],
    mistakes: ['Levantar el cuerpo de la almohadilla', 'Cortar el recorrido abajo'],
    alternatives: ['inclineCurl'],
  },
  reversePreacher: {
    gym: true,
    name: 'Curl invertido en predicador (antebrazo)',
    img: 'Reverse_Barbell_Preacher_Curls',
    primary: ['forearms'],
    secondary: ['biceps'],
    increment: 1,
    why: 'Agarre prono: trabaja braquiorradial y extensores del antebrazo.',
    cues: ['Palmas hacia abajo, brazos apoyados en el predicador.', 'Sube sin mover los codos y baja lento.'],
    mistakes: ['Doblar las muñecas', 'Balancear'],
    alternatives: [],
  },
  machineRow: {
    gym: true,
    name: 'Remo en máquina',
    img: 'Leverage_Iso_Row',
    primary: ['back'],
    secondary: ['biceps', 'rearDelts'],
    increment: 2.5,
    why: 'Espalda media con el pecho apoyado: sin fatiga lumbar y fácil de progresar.',
    cues: ['Pecho contra el apoyo.', 'Brazos estirados al empezar, dejando que las escápulas se separen.', 'Lleva los codos atrás pegados al cuerpo y junta las escápulas.'],
    mistakes: ['Despegar el pecho', 'Tirar solo con los brazos'],
    alternatives: ['chestSupportedRow', 'cableRow'],
  },
  assistedChin: {
    gym: true, assisted: true,
    name: 'Dominada asistida',
    img: 'Chin-Up',
    primary: ['back'],
    secondary: ['biceps'],
    increment: 2.5,
    why: 'Dorsales y bíceps. Aquí el peso es la ayuda: progresar = usar MENOS asistencia.',
    cues: ['Rodillas en la plataforma, cuelga con los brazos estirados.', 'Tira de los codos hacia las costillas hasta pasar la barbilla.', 'Baja controlado hasta estirar del todo.'],
    mistakes: ['Medias repeticiones', 'Balancearse'],
    alternatives: ['latPulldown', 'pullups'],
  },
  assistedDip: {
    gym: true, assisted: true,
    name: 'Fondo asistido',
    img: 'Dips_-_Triceps_Version',
    primary: ['chest', 'triceps'],
    secondary: [],
    increment: 2.5,
    why: 'Pecho bajo y tríceps con gran estiramiento. El peso es la ayuda: progresar = MENOS asistencia.',
    cues: ['Torso algo inclinado hacia delante para más pecho.', 'Baja hasta que el hombro quede a la altura del codo o un poco más, sin molestia.', 'Sube sin encoger los hombros.'],
    mistakes: ['Bajar poco', 'Encoger los hombros'],
    alternatives: ['dips'],
  },
  hipThrust: {
    leg: true,
    name: 'Hip thrust (opcional)',
    img: 'Barbell_Hip_Thrust',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    increment: 5,
    why: 'Glúteo casi sin cargar la tibia. Opcional: tus glúteos ya están muy desarrollados, así que no está en la rutina.',
    cues: ['Espalda alta en el banco, pies a la anchura de la cadera.', 'Sube hasta alinear rodillas, cadera y hombros; aprieta 1 s.'],
    mistakes: ['Arquear la zona lumbar', 'Pies muy lejos o muy cerca'],
    alternatives: [],
  },
  backExtension: {
    leg: true,
    name: 'Hiperextensión 45°',
    img: 'Hyperextensions_Back_Extensions',
    primary: ['hamstrings', 'glutes'],
    secondary: ['back'],
    increment: 2.5,
    why: 'Isquios y glúteos en estiramiento, con muy poca carga sobre la tibia.',
    cues: ['Cadera justo por encima del apoyo.', 'Baja flexionando la cadera con la espalda neutra.', 'Sube hasta alinear el cuerpo, sin hiperextender.'],
    mistakes: ['Redondear la espalda', 'Subir de más arqueando la zona lumbar'],
    alternatives: ['rdl'],
  },
};

// Cada "slot" es un hueco de la rutina que el usuario puede sustituir por una alternativa.
// superset: slots con la misma letra se alternan con descanso corto.
// Rutina adaptada a las máquinas de tu gimnasio y a la recuperación de la pierna.
export const ROUTINES = {
  A: {
    name: 'Full Body A',
    slots: [
      { id: 'A1', exercise: 'hsLegPress', sets: 3, reps: [10, 15], rest: 150 },
      { id: 'A2', exercise: 'hsInclinePress', sets: 3, reps: [6, 10], rest: 150 },
      { id: 'A3', exercise: 'assistedChin', sets: 4, reps: [6, 10], rest: 150 },
      { id: 'A4', exercise: 'seatedLegCurl', sets: 3, reps: [10, 15], rest: 90 },
      { id: 'A5', exercise: 'machineLateral', sets: 3, reps: [12, 20], rest: 60 },
      { id: 'A6', exercise: 'machineTriceps', sets: 3, reps: [10, 15], rest: 60, superset: 'x' },
      { id: 'A7', exercise: 'machineCurl', sets: 3, reps: [10, 15], rest: 60, superset: 'x' },
      { id: 'A8', exercise: 'calfExtension', sets: 3, reps: [12, 20], rest: 60 },
    ],
  },
  B: {
    name: 'Full Body B',
    slots: [
      { id: 'B1', exercise: 'hackSquat', sets: 3, reps: [10, 15], rest: 150 },
      { id: 'B2', exercise: 'seatedLegCurl', sets: 3, reps: [10, 15], rest: 90 },
      { id: 'B3', exercise: 'assistedDip', sets: 3, reps: [6, 10], rest: 150 },
      { id: 'B4', exercise: 'machineRow', sets: 4, reps: [8, 12], rest: 120 },
      { id: 'B5', exercise: 'pecFly', sets: 3, reps: [10, 15], rest: 75 },
      { id: 'B6', exercise: 'machineLateral', sets: 3, reps: [12, 20], rest: 60, superset: 'y' },
      { id: 'B7', exercise: 'rearDeltFly', sets: 2, reps: [12, 20], rest: 60, superset: 'y' },
      { id: 'B8', exercise: 'reversePreacher', sets: 2, reps: [10, 15], rest: 60 },
      { id: 'B9', exercise: 'calfExtension', sets: 3, reps: [12, 20], rest: 60 },
    ],
  },
};

// Lo que la app "recuerda" de ti. Editable en Ajustes → Tu perfil.
export const DEFAULT_PROFILE = {
  injuredSide: null, // 'L' | 'R'
  bodyweight: null, // kg, para calcular la carga real en ejercicios asistidos
  recovery: true,
  notes: [
    'Entreno 2 (máximo 3) días por semana.',
    'Hace ~3 meses: fractura incompleta de tibia y algo de astillamiento en el fémur. Controlar pesos en piernas.',
    'Hago los ejercicios de pierna de un lado y luego del otro, empezando por la lesionada.',
    'Glúteos ya muy desarrollados (montaña + muchas sentadillas en el colegio): no priorizar glúteo; hip thrust opcional.',
    'Prioridades: isquios (curl femoral sentado 2×/semana), hombro lateral y espalda.',
    'Máquinas: Hammer Strength incline press y prensa, hack squat, pectoral fly/rear delt, elevación lateral, extensión de tríceps y curl de bíceps (Life Fitness), remo, dominadas y fondos asistidos, curl femoral sentado, extensión de gemelos, predicador.',
  ].join('\n'),
};

// Recuperación: umbral de dolor (0–10) por encima del cual se frena la progresión.
export const PAIN_LIMIT = 3;

export function imgUrl(exerciseId, frame = 0) {
  return `img/ex/${EXERCISES[exerciseId].img}/${frame}.jpg`;
}
